# Site settings
title: title
email: email.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

default:
  -
  scope:
    path: ""
    type: "members"
  values:
    _options:
      image_path:
        width: 440
        height: 440
        uploads_dir: "/images/members"
